services:
  # L'API Python (Le Cerveau)
  cv-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: smart-cv-app:latest # On donne un nom fixe à l'image
    container_name: cv-finaxys-api
    ports:
      - "8000:8000"
    volumes:
      - ./output:/app/output
      - ./vector_db:/app/vector_db
      - ./logs:/app/logs
      - ./input:/app/input
    environment:
      - DISABLE_DOCLING=1
    env_file: .env
    restart: always

  # Le Bot Telegram (Utilise la MÊME image que l'API)
  cv-bot:
    image: smart-cv-app:latest # Utilise l'image construite par cv-api
    container_name: cv-finaxys-bot
    command: python bot.py
    volumes:
      - ./output:/app/output
      - ./vector_db:/app/vector_db
      - ./logs:/app/logs
      - ./input:/app/input
    environment:
      - DISABLE_HEALTHCHECK=true
    env_file: .env
    depends_on:
      - cv-api
    restart: always
